// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"github.com/dipper-iot/dipper-engine-server/ent/predicate"
	"github.com/dipper-iot/dipper-engine-server/ent/rulechan"
	"github.com/dipper-iot/dipper-engine-server/ent/rulenode"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeRuleChan = "RuleChan"
	TypeRuleNode = "RuleNode"
)

// RuleChanMutation represents an operation that mutates the RuleChan nodes in the graph.
type RuleChanMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	root_node     *string
	status        *rulechan.Status
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	rules         map[int]struct{}
	removedrules  map[int]struct{}
	clearedrules  bool
	done          bool
	oldValue      func(context.Context) (*RuleChan, error)
	predicates    []predicate.RuleChan
}

var _ ent.Mutation = (*RuleChanMutation)(nil)

// rulechanOption allows management of the mutation configuration using functional options.
type rulechanOption func(*RuleChanMutation)

// newRuleChanMutation creates new mutation for the RuleChan entity.
func newRuleChanMutation(c config, op Op, opts ...rulechanOption) *RuleChanMutation {
	m := &RuleChanMutation{
		config:        c,
		op:            op,
		typ:           TypeRuleChan,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRuleChanID sets the ID field of the mutation.
func withRuleChanID(id int) rulechanOption {
	return func(m *RuleChanMutation) {
		var (
			err   error
			once  sync.Once
			value *RuleChan
		)
		m.oldValue = func(ctx context.Context) (*RuleChan, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().RuleChan.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRuleChan sets the old RuleChan of the mutation.
func withRuleChan(node *RuleChan) rulechanOption {
	return func(m *RuleChanMutation) {
		m.oldValue = func(context.Context) (*RuleChan, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RuleChanMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RuleChanMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RuleChanMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RuleChanMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().RuleChan.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *RuleChanMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *RuleChanMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the RuleChan entity.
// If the RuleChan object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleChanMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *RuleChanMutation) ResetName() {
	m.name = nil
}

// SetRootNode sets the "root_node" field.
func (m *RuleChanMutation) SetRootNode(s string) {
	m.root_node = &s
}

// RootNode returns the value of the "root_node" field in the mutation.
func (m *RuleChanMutation) RootNode() (r string, exists bool) {
	v := m.root_node
	if v == nil {
		return
	}
	return *v, true
}

// OldRootNode returns the old "root_node" field's value of the RuleChan entity.
// If the RuleChan object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleChanMutation) OldRootNode(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRootNode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRootNode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRootNode: %w", err)
	}
	return oldValue.RootNode, nil
}

// ResetRootNode resets all changes to the "root_node" field.
func (m *RuleChanMutation) ResetRootNode() {
	m.root_node = nil
}

// SetStatus sets the "status" field.
func (m *RuleChanMutation) SetStatus(r rulechan.Status) {
	m.status = &r
}

// Status returns the value of the "status" field in the mutation.
func (m *RuleChanMutation) Status() (r rulechan.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the RuleChan entity.
// If the RuleChan object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleChanMutation) OldStatus(ctx context.Context) (v rulechan.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *RuleChanMutation) ResetStatus() {
	m.status = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *RuleChanMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *RuleChanMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the RuleChan entity.
// If the RuleChan object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleChanMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *RuleChanMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *RuleChanMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *RuleChanMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the RuleChan entity.
// If the RuleChan object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleChanMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *RuleChanMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddRuleIDs adds the "rules" edge to the RuleNode entity by ids.
func (m *RuleChanMutation) AddRuleIDs(ids ...int) {
	if m.rules == nil {
		m.rules = make(map[int]struct{})
	}
	for i := range ids {
		m.rules[ids[i]] = struct{}{}
	}
}

// ClearRules clears the "rules" edge to the RuleNode entity.
func (m *RuleChanMutation) ClearRules() {
	m.clearedrules = true
}

// RulesCleared reports if the "rules" edge to the RuleNode entity was cleared.
func (m *RuleChanMutation) RulesCleared() bool {
	return m.clearedrules
}

// RemoveRuleIDs removes the "rules" edge to the RuleNode entity by IDs.
func (m *RuleChanMutation) RemoveRuleIDs(ids ...int) {
	if m.removedrules == nil {
		m.removedrules = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.rules, ids[i])
		m.removedrules[ids[i]] = struct{}{}
	}
}

// RemovedRules returns the removed IDs of the "rules" edge to the RuleNode entity.
func (m *RuleChanMutation) RemovedRulesIDs() (ids []int) {
	for id := range m.removedrules {
		ids = append(ids, id)
	}
	return
}

// RulesIDs returns the "rules" edge IDs in the mutation.
func (m *RuleChanMutation) RulesIDs() (ids []int) {
	for id := range m.rules {
		ids = append(ids, id)
	}
	return
}

// ResetRules resets all changes to the "rules" edge.
func (m *RuleChanMutation) ResetRules() {
	m.rules = nil
	m.clearedrules = false
	m.removedrules = nil
}

// Where appends a list predicates to the RuleChanMutation builder.
func (m *RuleChanMutation) Where(ps ...predicate.RuleChan) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *RuleChanMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (RuleChan).
func (m *RuleChanMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RuleChanMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.name != nil {
		fields = append(fields, rulechan.FieldName)
	}
	if m.root_node != nil {
		fields = append(fields, rulechan.FieldRootNode)
	}
	if m.status != nil {
		fields = append(fields, rulechan.FieldStatus)
	}
	if m.created_at != nil {
		fields = append(fields, rulechan.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, rulechan.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RuleChanMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case rulechan.FieldName:
		return m.Name()
	case rulechan.FieldRootNode:
		return m.RootNode()
	case rulechan.FieldStatus:
		return m.Status()
	case rulechan.FieldCreatedAt:
		return m.CreatedAt()
	case rulechan.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RuleChanMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case rulechan.FieldName:
		return m.OldName(ctx)
	case rulechan.FieldRootNode:
		return m.OldRootNode(ctx)
	case rulechan.FieldStatus:
		return m.OldStatus(ctx)
	case rulechan.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case rulechan.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown RuleChan field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RuleChanMutation) SetField(name string, value ent.Value) error {
	switch name {
	case rulechan.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case rulechan.FieldRootNode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRootNode(v)
		return nil
	case rulechan.FieldStatus:
		v, ok := value.(rulechan.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case rulechan.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case rulechan.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown RuleChan field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RuleChanMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RuleChanMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RuleChanMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown RuleChan numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RuleChanMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RuleChanMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RuleChanMutation) ClearField(name string) error {
	return fmt.Errorf("unknown RuleChan nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RuleChanMutation) ResetField(name string) error {
	switch name {
	case rulechan.FieldName:
		m.ResetName()
		return nil
	case rulechan.FieldRootNode:
		m.ResetRootNode()
		return nil
	case rulechan.FieldStatus:
		m.ResetStatus()
		return nil
	case rulechan.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case rulechan.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown RuleChan field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RuleChanMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.rules != nil {
		edges = append(edges, rulechan.EdgeRules)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RuleChanMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case rulechan.EdgeRules:
		ids := make([]ent.Value, 0, len(m.rules))
		for id := range m.rules {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RuleChanMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedrules != nil {
		edges = append(edges, rulechan.EdgeRules)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RuleChanMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case rulechan.EdgeRules:
		ids := make([]ent.Value, 0, len(m.removedrules))
		for id := range m.removedrules {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RuleChanMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedrules {
		edges = append(edges, rulechan.EdgeRules)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RuleChanMutation) EdgeCleared(name string) bool {
	switch name {
	case rulechan.EdgeRules:
		return m.clearedrules
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RuleChanMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown RuleChan unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RuleChanMutation) ResetEdge(name string) error {
	switch name {
	case rulechan.EdgeRules:
		m.ResetRules()
		return nil
	}
	return fmt.Errorf("unknown RuleChan edge %s", name)
}

// RuleNodeMutation represents an operation that mutates the RuleNode nodes in the graph.
type RuleNodeMutation struct {
	config
	op            Op
	typ           string
	id            *int
	node_id       *string
	option        *map[string]interface{}
	debug         *bool
	end           *bool
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	chain         *int
	clearedchain  bool
	done          bool
	oldValue      func(context.Context) (*RuleNode, error)
	predicates    []predicate.RuleNode
}

var _ ent.Mutation = (*RuleNodeMutation)(nil)

// rulenodeOption allows management of the mutation configuration using functional options.
type rulenodeOption func(*RuleNodeMutation)

// newRuleNodeMutation creates new mutation for the RuleNode entity.
func newRuleNodeMutation(c config, op Op, opts ...rulenodeOption) *RuleNodeMutation {
	m := &RuleNodeMutation{
		config:        c,
		op:            op,
		typ:           TypeRuleNode,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRuleNodeID sets the ID field of the mutation.
func withRuleNodeID(id int) rulenodeOption {
	return func(m *RuleNodeMutation) {
		var (
			err   error
			once  sync.Once
			value *RuleNode
		)
		m.oldValue = func(ctx context.Context) (*RuleNode, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().RuleNode.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRuleNode sets the old RuleNode of the mutation.
func withRuleNode(node *RuleNode) rulenodeOption {
	return func(m *RuleNodeMutation) {
		m.oldValue = func(context.Context) (*RuleNode, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RuleNodeMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RuleNodeMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RuleNodeMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RuleNodeMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().RuleNode.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetChainID sets the "chain_id" field.
func (m *RuleNodeMutation) SetChainID(i int) {
	m.chain = &i
}

// ChainID returns the value of the "chain_id" field in the mutation.
func (m *RuleNodeMutation) ChainID() (r int, exists bool) {
	v := m.chain
	if v == nil {
		return
	}
	return *v, true
}

// OldChainID returns the old "chain_id" field's value of the RuleNode entity.
// If the RuleNode object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleNodeMutation) OldChainID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldChainID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldChainID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldChainID: %w", err)
	}
	return oldValue.ChainID, nil
}

// ClearChainID clears the value of the "chain_id" field.
func (m *RuleNodeMutation) ClearChainID() {
	m.chain = nil
	m.clearedFields[rulenode.FieldChainID] = struct{}{}
}

// ChainIDCleared returns if the "chain_id" field was cleared in this mutation.
func (m *RuleNodeMutation) ChainIDCleared() bool {
	_, ok := m.clearedFields[rulenode.FieldChainID]
	return ok
}

// ResetChainID resets all changes to the "chain_id" field.
func (m *RuleNodeMutation) ResetChainID() {
	m.chain = nil
	delete(m.clearedFields, rulenode.FieldChainID)
}

// SetNodeID sets the "node_id" field.
func (m *RuleNodeMutation) SetNodeID(s string) {
	m.node_id = &s
}

// NodeID returns the value of the "node_id" field in the mutation.
func (m *RuleNodeMutation) NodeID() (r string, exists bool) {
	v := m.node_id
	if v == nil {
		return
	}
	return *v, true
}

// OldNodeID returns the old "node_id" field's value of the RuleNode entity.
// If the RuleNode object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleNodeMutation) OldNodeID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNodeID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNodeID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNodeID: %w", err)
	}
	return oldValue.NodeID, nil
}

// ResetNodeID resets all changes to the "node_id" field.
func (m *RuleNodeMutation) ResetNodeID() {
	m.node_id = nil
}

// SetOption sets the "option" field.
func (m *RuleNodeMutation) SetOption(value map[string]interface{}) {
	m.option = &value
}

// Option returns the value of the "option" field in the mutation.
func (m *RuleNodeMutation) Option() (r map[string]interface{}, exists bool) {
	v := m.option
	if v == nil {
		return
	}
	return *v, true
}

// OldOption returns the old "option" field's value of the RuleNode entity.
// If the RuleNode object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleNodeMutation) OldOption(ctx context.Context) (v map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOption is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOption requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOption: %w", err)
	}
	return oldValue.Option, nil
}

// ResetOption resets all changes to the "option" field.
func (m *RuleNodeMutation) ResetOption() {
	m.option = nil
}

// SetDebug sets the "debug" field.
func (m *RuleNodeMutation) SetDebug(b bool) {
	m.debug = &b
}

// Debug returns the value of the "debug" field in the mutation.
func (m *RuleNodeMutation) Debug() (r bool, exists bool) {
	v := m.debug
	if v == nil {
		return
	}
	return *v, true
}

// OldDebug returns the old "debug" field's value of the RuleNode entity.
// If the RuleNode object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleNodeMutation) OldDebug(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDebug is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDebug requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDebug: %w", err)
	}
	return oldValue.Debug, nil
}

// ResetDebug resets all changes to the "debug" field.
func (m *RuleNodeMutation) ResetDebug() {
	m.debug = nil
}

// SetEnd sets the "end" field.
func (m *RuleNodeMutation) SetEnd(b bool) {
	m.end = &b
}

// End returns the value of the "end" field in the mutation.
func (m *RuleNodeMutation) End() (r bool, exists bool) {
	v := m.end
	if v == nil {
		return
	}
	return *v, true
}

// OldEnd returns the old "end" field's value of the RuleNode entity.
// If the RuleNode object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleNodeMutation) OldEnd(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEnd is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEnd requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnd: %w", err)
	}
	return oldValue.End, nil
}

// ResetEnd resets all changes to the "end" field.
func (m *RuleNodeMutation) ResetEnd() {
	m.end = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *RuleNodeMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *RuleNodeMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the RuleNode entity.
// If the RuleNode object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleNodeMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *RuleNodeMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *RuleNodeMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *RuleNodeMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the RuleNode entity.
// If the RuleNode object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleNodeMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *RuleNodeMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// ClearChain clears the "chain" edge to the RuleChan entity.
func (m *RuleNodeMutation) ClearChain() {
	m.clearedchain = true
}

// ChainCleared reports if the "chain" edge to the RuleChan entity was cleared.
func (m *RuleNodeMutation) ChainCleared() bool {
	return m.ChainIDCleared() || m.clearedchain
}

// ChainIDs returns the "chain" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// ChainID instead. It exists only for internal usage by the builders.
func (m *RuleNodeMutation) ChainIDs() (ids []int) {
	if id := m.chain; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetChain resets all changes to the "chain" edge.
func (m *RuleNodeMutation) ResetChain() {
	m.chain = nil
	m.clearedchain = false
}

// Where appends a list predicates to the RuleNodeMutation builder.
func (m *RuleNodeMutation) Where(ps ...predicate.RuleNode) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *RuleNodeMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (RuleNode).
func (m *RuleNodeMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RuleNodeMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.chain != nil {
		fields = append(fields, rulenode.FieldChainID)
	}
	if m.node_id != nil {
		fields = append(fields, rulenode.FieldNodeID)
	}
	if m.option != nil {
		fields = append(fields, rulenode.FieldOption)
	}
	if m.debug != nil {
		fields = append(fields, rulenode.FieldDebug)
	}
	if m.end != nil {
		fields = append(fields, rulenode.FieldEnd)
	}
	if m.created_at != nil {
		fields = append(fields, rulenode.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, rulenode.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RuleNodeMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case rulenode.FieldChainID:
		return m.ChainID()
	case rulenode.FieldNodeID:
		return m.NodeID()
	case rulenode.FieldOption:
		return m.Option()
	case rulenode.FieldDebug:
		return m.Debug()
	case rulenode.FieldEnd:
		return m.End()
	case rulenode.FieldCreatedAt:
		return m.CreatedAt()
	case rulenode.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RuleNodeMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case rulenode.FieldChainID:
		return m.OldChainID(ctx)
	case rulenode.FieldNodeID:
		return m.OldNodeID(ctx)
	case rulenode.FieldOption:
		return m.OldOption(ctx)
	case rulenode.FieldDebug:
		return m.OldDebug(ctx)
	case rulenode.FieldEnd:
		return m.OldEnd(ctx)
	case rulenode.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case rulenode.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown RuleNode field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RuleNodeMutation) SetField(name string, value ent.Value) error {
	switch name {
	case rulenode.FieldChainID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetChainID(v)
		return nil
	case rulenode.FieldNodeID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNodeID(v)
		return nil
	case rulenode.FieldOption:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOption(v)
		return nil
	case rulenode.FieldDebug:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDebug(v)
		return nil
	case rulenode.FieldEnd:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnd(v)
		return nil
	case rulenode.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case rulenode.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown RuleNode field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RuleNodeMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RuleNodeMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RuleNodeMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown RuleNode numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RuleNodeMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(rulenode.FieldChainID) {
		fields = append(fields, rulenode.FieldChainID)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RuleNodeMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RuleNodeMutation) ClearField(name string) error {
	switch name {
	case rulenode.FieldChainID:
		m.ClearChainID()
		return nil
	}
	return fmt.Errorf("unknown RuleNode nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RuleNodeMutation) ResetField(name string) error {
	switch name {
	case rulenode.FieldChainID:
		m.ResetChainID()
		return nil
	case rulenode.FieldNodeID:
		m.ResetNodeID()
		return nil
	case rulenode.FieldOption:
		m.ResetOption()
		return nil
	case rulenode.FieldDebug:
		m.ResetDebug()
		return nil
	case rulenode.FieldEnd:
		m.ResetEnd()
		return nil
	case rulenode.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case rulenode.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown RuleNode field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RuleNodeMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.chain != nil {
		edges = append(edges, rulenode.EdgeChain)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RuleNodeMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case rulenode.EdgeChain:
		if id := m.chain; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RuleNodeMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RuleNodeMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RuleNodeMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedchain {
		edges = append(edges, rulenode.EdgeChain)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RuleNodeMutation) EdgeCleared(name string) bool {
	switch name {
	case rulenode.EdgeChain:
		return m.clearedchain
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RuleNodeMutation) ClearEdge(name string) error {
	switch name {
	case rulenode.EdgeChain:
		m.ClearChain()
		return nil
	}
	return fmt.Errorf("unknown RuleNode unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RuleNodeMutation) ResetEdge(name string) error {
	switch name {
	case rulenode.EdgeChain:
		m.ResetChain()
		return nil
	}
	return fmt.Errorf("unknown RuleNode edge %s", name)
}
