// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dipper-iot/dipper-engine-server/ent/predicate"
	"github.com/dipper-iot/dipper-engine-server/ent/rulenode"
)

// RuleNodeDelete is the builder for deleting a RuleNode entity.
type RuleNodeDelete struct {
	config
	hooks    []Hook
	mutation *RuleNodeMutation
}

// Where appends a list predicates to the RuleNodeDelete builder.
func (rnd *RuleNodeDelete) Where(ps ...predicate.RuleNode) *RuleNodeDelete {
	rnd.mutation.Where(ps...)
	return rnd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rnd *RuleNodeDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(rnd.hooks) == 0 {
		affected, err = rnd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RuleNodeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rnd.mutation = mutation
			affected, err = rnd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(rnd.hooks) - 1; i >= 0; i-- {
			if rnd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rnd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rnd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (rnd *RuleNodeDelete) ExecX(ctx context.Context) int {
	n, err := rnd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rnd *RuleNodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: rulenode.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: rulenode.FieldID,
			},
		},
	}
	if ps := rnd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rnd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// RuleNodeDeleteOne is the builder for deleting a single RuleNode entity.
type RuleNodeDeleteOne struct {
	rnd *RuleNodeDelete
}

// Exec executes the deletion query.
func (rndo *RuleNodeDeleteOne) Exec(ctx context.Context) error {
	n, err := rndo.rnd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rulenode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rndo *RuleNodeDeleteOne) ExecX(ctx context.Context) {
	rndo.rnd.ExecX(ctx)
}
