// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// RuleChan is the predicate function for rulechan builders.
type RuleChan func(*sql.Selector)

// RuleNode is the predicate function for rulenode builders.
type RuleNode func(*sql.Selector)
